name: Publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'images/**'
      - 'examples/**'
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  verify:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: Install Dependencies
        run: pnpm install
      - name: Check Formatting
        run: pnpm format:check
      - name: Build Packages
        run: pnpm -r build:clean
      - name: Build Typescript
        run: pnpm build:clean
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
